Feature/us014 add parkingslots preate action
SardorBozorov/ParkingZone pull request #15
Opened 2024-05-15 11:45 UTC by SardorBozorov

2024-05-16 07:30 UTC, SamanKingDotNetDeveloper approved these changes

2024-05-16 07:30 UTC, SamanKingDotNetDeveloper commented on Parking_Zone.Test/ModelValidationtests/ParkingSlots/CreateVMTest.cs
> +                new object[] { 5, new ParkingSlotCategory(), false, 20, true },
give here value just one of the categories like ParkingSlotCategorty.VIP or .Business do not just call the class

2024-05-16 10:39 UTC, dotnetdew requested changes

2024-05-16 10:39 UTC, dotnetdew commented on ParkingZone/Areas/Admin/Controllers/ParkingSlotController.cs
> +            ParkingZoneId = parkingZoneId,
what if I give here not existing parking zone? so that means we should check wheter zone exists or not

2024-05-16 10:39 UTC, dotnetdew commented on ParkingZone/Areas/Admin/Controllers/ParkingSlotController.cs
> +    {
write a method that checks for slot number. if I enter existing number in database it should give model state error

2024-05-16 10:39 UTC, dotnetdew commented on ParkingZone/Areas/Admin/Views/ParkingSlot/Create.cshtml
> +<h1>Create a new Parking Slot</h1>
add Name of Parking Zone. we should know for what parking zone we are adding

2024-05-16 10:39 UTC, dotnetdew commented on ParkingZone/Areas/Admin/Views/ParkingSlot/Create.cshtml
> +<h4>CreateVM</h4>
```suggestion
```

2024-05-16 10:39 UTC, dotnetdew commented on ParkingZone/Areas/Admin/Views/ParkingSlot/Create.cshtml
> +<h4>CreateVM</h4>
users dont understand what is view model

2024-05-17 06:40 UTC, dotnetdew approved these changes

2024-05-17 07:18 UTC, merged