Parking Slot edit action added
SardorBozorov/ParkingZone pull request #16
Opened 2024-05-17 10:34 UTC by SardorBozorov

2024-05-17 10:41 UTC, iamurtazo commented on ParkingZone/Models/ParkingSlotVMs/EditVM.cs
> +    { }
```suggestion
public EditVm() {} lets keep it like this in line 18
```

2024-05-17 10:44 UTC, iamurtazo commented on Parking_Zone.Test/ModelValidationtests/ParkingSlots/EditVMTest.cs
> +
space

2024-05-17 15:14 UTC, dilmurod-rozikov requested changes

2024-05-17 15:14 UTC, dilmurod-rozikov commented on ParkingZone/Areas/Admin/Controllers/ParkingSlotController.cs
> +    }
put a space after closing braces

2024-05-17 15:14 UTC, dilmurod-rozikov commented on ParkingZone/Models/ParkingSlotVMs/EditVM.cs
> +    public ParkingSlot MapToModel(ParkingSlot Vm)
public ParkingSlot MapToModel(ParkingSlot Vm)
```suggestion
    public ParkingSlot MapToModel(ParkingSlot slot)
```

2024-05-17 15:14 UTC, dilmurod-rozikov commented on Parking_Zone.Test/Controllers/ParkingSlotControllerTest.cs
> +        //Arrange
```suggestion
               //Arrange
```
put a space

2024-05-17 21:21 UTC, SamDotNetDev requested changes

2024-05-17 21:21 UTC, SamDotNetDev commented on Parking_Zone.Test/Controllers/ParkingSlotControllerTest.cs
> +        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenReturnNotFoundIfIdAndSlotIdDoesNotMatch()
NamingConvention error 
```suggestion
        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenIdAndSlotIdDoNotMatchAndReturnsNotFound()
```

2024-05-17 21:21 UTC, SamDotNetDev commented on Parking_Zone.Test/Controllers/ParkingSlotControllerTest.cs
> +        public void GivenParkingSlotId_WhenEditGetIsCalled_ThenReturnViewResult()
```suggestion
        public void GivenParkingSlotId_WhenEditIsCalled_ThenReturnsViewResult()
```

2024-05-17 21:21 UTC, SamDotNetDev commented on Parking_Zone.Test/Controllers/ParkingSlotControllerTest.cs
> +        public void GivenParkingSlotId_WhenEditGetIsCalled_ThenReturnNotFound()
Returns

2024-05-17 21:21 UTC, SamDotNetDev commented on Parking_Zone.Test/Controllers/ParkingSlotControllerTest.cs
> +        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenReturnNotFoundIfSlotIsNull()
Same fix naming

2024-05-18 03:20 UTC, dilmurod-rozikov approved these changes

2024-05-20 04:40 UTC, dotnetdew approved these changes

2024-05-20 04:57 UTC, merged